<?php
/**
 * Created by PhpStorm.
 * User: ralph
 * Date: 16.02.17
 * Time: 17:08
 */

/**
 * Import field formatters.
 */
require_once 'includes/field_formatter.lib.inc';

/**
 * Import image styles (ImageMagick styles), if imagemagick module is installed
 */
if (module_exists('imagemagick')) {
  require_once 'includes/image_style.lib.inc';
}

/**
 * Useful Webform enhancements.
 */
if (module_exists('webform')) {
  require_once 'includes/webform.lib.inc';
}

/**
 * Import all social node importers.
 */
if (module_exists('twitter') || module_exists('instagram_social_feed')) {
  require_once 'includes/social_nodes.importer.inc';
}


/* --------------------------------------------------
 * Hooks implementations
 * --------------------------------------------------*/

/**
 * Implements hook_theme().
 */
function pxl_hooks_theme() {
  return array(
    // The theme function that our formatter uses:
    'pxl_hooks_date_von_bis_formatter' => array(
      // Don't forget that all Drupal 7 theme functions have only one argument,
      // so you declare what variables get passed within that argument instead.
      // See http://drupal.org/node/224333#theme_changes
      'variables' => array('element' => NULL),
      'file' => 'includes/field_formatter.lib.inc',
    ),
    'pxl_hooks_date_start_ende_formatter' => array(
      // Don't forget that all Drupal 7 theme functions have only one argument,
      // so you declare what variables get passed within that argument instead.
      // See http://drupal.org/node/224333#theme_changes
      'variables' => array('element' => NULL),
      'file' => 'includes/field_formatter.lib.inc',
    ),
  );
}

/**
 * Override front page according to campaign settings.
 *
 * @param $node
 */
function pxl_hooks_node_presave($node) {
  if ($node->type != 'campaign') return;

  if ($node->field_current_campaign[LANGUAGE_NONE][0]['value']) {
    //
    // reset current main campaign
    $front_path = variable_get('site_frontpage');
    $parts = explode('/', $front_path);
    $current_nid = array_pop($parts);
    $current_node = node_load($current_nid);
    $current_node->field_current_campaign[LANGUAGE_NONE][0]['value'] = 0;
    field_attach_update('node', $current_node);

    //
    // set new main campaign as front page
    variable_set('site_frontpage', "node/{$node->nid}");
  }

}
